apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  host: {{ include "hello-world.fullname" . }}-app.k8s.sndevops.xyz
  prefix: /
  service: {{ include "hello-world.fullname" . }}.svc.cluster.local:8{{ .Values.service.port }}