apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}-argo-app.k8s.sndevops.xyz
  prefix: /
  service: {{ include "hello-world.fullname" . }}.default.svc.cluster.local:{{ .Values.service.port }}